scenario:
  name: "Satellite and Ground Station Simulation"
  description: "Simulated satellite and ground station data handling"
  version: "1.0"

instance_id: "instance_123"  # Unique ID for the scenario

config_location: "/opt/scse_assets/{id}/config.yaml"  # Template for config file location

controller:
  ip: "172.20.10.4"
  port: 5002
  base_directory: "/opt/scse_dms/instance_123"

assets:
  - name: "Satellite 1"
    id: "asset_1"
    ip: "172.20.10.2"
    port: 5000
    base_directory: "/opt/scse_assets/asset_1"
    retrieval_directories:
      telemetry: "asset_data/retrieval/telemetry"
      images: "asset_data/retrieval/images"
    sending_directories:
      data: "asset_data/sending/data"
    data_types:
      - name: "telemetry"
        frequency: 20  # in seconds
      - name: "images"
        frequency: 30  # in seconds
    logging:
      level: "INFO"
      log_file: "asset_data/logs/satellite1_log.log"
    config_file: "/opt/scse_assets/asset_1/config.yaml"

  - name: "Ground Station 1"
    id: "asset_2"
    ip: "172.20.10.3"
    port: 5001
    base_directory: "/opt/scse_assets/asset_2"
    retrieval_directories:
      connection_window: "asset_data/retrieval/connection_window"
    sending_directories:
      telemetry: "asset_data/sending/telemetry"
    data_types:
      - name: "telemetry"
        frequency: 20  # in seconds
    logging:
      level: "INFO"
      log_file: "asset_data/logs/ground_station1_log.log"
    config_file: "/opt/scse_assets/asset_2/config.yaml"
